from dao.BaseEngine import MetaBase
from sqlalchemy.orm import relationship
from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey

class BizConditionsMaster(MetaBase):
    __tablename__ = "bizconditionsmaster"
    # customerCd: str = Column(String)
    customerCd: str = Column(String, ForeignKey("customermaster.customerCd"), primary_key=True)
    # customerCd: str = Column("customerCd",String, ForeignKey("customermaster.customerCd", onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
    mainCustomer_1: str = Column(String)
    mainCustomer_2: str = Column(String)
    mainCustomer_3: str = Column(String)
    mainCustomer_4: str = Column(String)
    mainCustomer_5: str = Column(String)
    curPrdYear: str = Column(String)
    curPrdSales_1: int = Column(Integer)
    curPrdSales_2: int = Column(Integer)
    curPrdSales_3: int = Column(Integer)
    curPrdSales_4: int = Column(Integer)
    curPrdSales_5: int = Column(Integer)
    curPrdSales_Our: int = Column(Integer)
    curPrdSales_Other: int = Column(Integer)
    curPrdSalesRatio_1: float = Column(Float)
    curPrdSalesRatio_2: float = Column(Float)
    curPrdSalesRatio_3: float = Column(Float)
    curPrdSalesRatio_4: float = Column(Float)
    curPrdSalesRatio_5: float = Column(Float)
    curPrdSalesRatio_Our: float = Column(Float)
    curPrdSalesRatio_Othor: float = Column(Float)
    curPrdSales_Sum: int = Column(Integer)
    curPrdOperatingProfit: int = Column(Integer)
    curPrdOrdinaryincome: int = Column(Integer)
    prevPrdYear: str = Column(String)
    prevPrdSales_1: int = Column(Integer)
    prevPrdSales_2: int = Column(Integer)
    prevPrdSales_3: int = Column(Integer)
    prevPrdSales_4: int = Column(Integer)
    prevPrdSales_5: int = Column(Integer)
    prevPrdSales_Our: int = Column(Integer)
    prevPrdSales_Other: int = Column(Integer)
    prevPrdSalesRatio_1: float = Column(Float)
    prevPrdSalesRatio_2: float = Column(Float)
    prevPrdSalesRatio_3: float = Column(Float)
    prevPrdSalesRatio_4: float = Column(Float)
    prevPrdSalesRatio_5: float = Column(Float)
    prevPrdSalesRatio_Our: float = Column(Float)
    prevPrdSalesRatio_Other: float = Column(Float)
    prevPrdSales_Sum: int = Column(Integer)
    prevPrdOperatingProfit: int = Column(Integer)
    prevPrdOrdinaryIncome: int = Column(Integer)
    lastPrdYear: str = Column(String)
    lastPrdSales_1: int = Column(Integer)
    lastPrdSales_2: int = Column(Integer)
    lastPrdSales_3: int = Column(Integer)
    lastPrdSales_4: int = Column(Integer)
    lastPrdSales_5: int = Column(Integer)
    lastPrdSales_Our: int = Column(Integer)
    lastPrdSales_Other: int = Column(Integer)
    lastPrdSalesRatio_1: float = Column(Float)
    lastPrdSalesRatio_2: float = Column(Float)
    lastPrdSalesRatio_3: float = Column(Float)
    lastPrdSalesRatio_4: float = Column(Float)
    lastPrdSalesRatio_5: float = Column(Float)
    lastPrdSalesRatio_Our: float = Column(Float)
    lastPrdSalesRatio_Other: float = Column(Float)
    lastPrdSales_sum: int = Column(Integer)
    lastPrdOperatingProfit: int = Column(Integer)
    lastPrdOrdinaryincome: int = Column(Integer)
    curPrdMainProducts: str = Column(String)

    def set_data(self, xldto):
        self.mainCustomer_1 = xldto.xlmainCustomer_1
        self.mainCustomer_2 = xldto.xlmainCustomer_2
        self.mainCustomer_3 = xldto.xlmainCustomer_3
        self.mainCustomer_4 = xldto.xlmainCustomer_4
        self.mainCustomer_5 = xldto.xlmainCustomer_5
